[build]
#target = "armv7-unknown-linux-gnueabihf"
target = "aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
# debian: needs `gcc-arm-linux-gnueabihf`
linker = "arm-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
# debian: needs `gcc-aarch64-linux-gnu`
linker = "aarch64-linux-gnu-gcc"

[env]
#PKG_CONFIG_SYSROOT_DIR="/usr/arm-linux-gnueabihf"
# uncomment this if using target "aarch64-unknown-linux-gnu"
PKG_CONFIG_SYSROOT_DIR="/usr/aarch64-linux-gnu"
