[build]
target = "armv7-unknown-linux-gnueabihf"
#target = "aarch64-unknown-linux-gnu"

[target.armv7-unknown-linux-gnueabihf]
linker = "armv7-linux-gnueabihf-gcc"

[target.aarch64-unknown-linux-gnu]
# debian: needs `aarch64-linux-gcc-gnu`
linker = "aarch64-linux-gnu-ld"
